- package.json
- src/config/server.js
- src/resources/discourse/discourse.service.js
- src/resources/message/message.controller.js
- src/resources/message/message.model.js
- src/resources/message/message.route.js
- src/resources/tool/data.model.js
- src/resources/topic/topic.controller.js
- src/resources/topic/topic.model.js
- src/resources/topic/topic.route.js
- src/resources/user/user.model.js
**PR**
Topics
- GET for all topics by user
- GET topic by Id (returns messages)
- PUT (not implemented as currently not updating the Topic model)
- POST to create topic
- DELETE to delete topic
Messages
- GET to return unread message count
- PUT update individual message by id
- POST to create messages
- DELETE to delete message by id
>  IG-552 and IG-553 - Messages and Topic APIs

- src/resources/discourse/discourse.route.js
- src/resources/discourse/discourse.service.js
- src/resources/message/message.controller.js
- src/resources/topic/topic.controller.js
**PR**
Added backend functionality for supporting message notifications
> IG-554 Notifications and messages

- src/resources/stats/kpis.router.js
- src/resources/stats/stats.router.js
**PR Includes changes to:**
- Technical MetaData is now retrieved from the database instead of CSV
- Test data has been excluded from both KPI and Stats endpoints
> IG-557 Remove test data from KPI and Stats

- swagger.yaml
Updated documentation with basic definitions for messages and topics endpoints for sign-off
> Added documentation for messages and topics

- src/resources/stats/kpis.router.js
- src/resources/stats/stats.router.js
Minor fix to lookups to exclude the test data from 'new access requests'
> IG-557 Remove Test data from stats

- src/resources/topic/topic.controller.js
V5 - page/ modal that appears before pre submission page supporting API changes
Based on data needed updates to the topic controller was needed.
> IG-566 Modifications to messages and topics

- src/resources/topic/topic.controller.js
Fix for messaging causing new messages not post correctly. Update to publisher and set title for topic title
> IG-566 Fix for publisher

- src/resources/datarequest/datarequest.model.js
- src/resources/datarequest/datarequest.route.js
- src/resources/publisher/publisher.controller.js
- src/resources/tool/data.model.js
- src/resources/utilities/emailGenerator.util.js
- Extended DAR model to support virtual dataset(s) and multiple datasets (datasetIds)
- Extended Data(tool) model to support virtual publisher
- Updated email generator to support multiple datasets in output
- Added additional DAR routes to support loading application forms from access ID (object _id), multiple concatenated datasetIds for multiple dataset applications, and modified single dataset route to return new 'about application' data
- Updated 'get all access requests for user' to return all applications for the user's DAR account area
> IG-572 - Finished backend work for multiple datasets and fixed QA issues

- src/resources/datarequest/datarequest.controller.js
- src/resources/datarequest/datarequest.model.js
- src/resources/datarequest/datarequest.route.js
- src/resources/message/message.controller.js
- src/resources/message/message.model.js
- src/resources/message/message.route.js
- src/resources/team/team.model.js
- src/resources/utilities/emailGenerator.util.js
- src/resources/utilities/notificationBuilder.js
**PR**
Approve and reject functionality for DAR including emails and notifications to custodian team and main applicant
**Solution**
- Added DAR controller to handle notification and email generation moving forward
- Updated DAR model application status enum to support approved, rejected and approved with conditions plus description for status to hold rejection reason or conditions
- Fixed defect in retrieving DAR for account area
- Added PUT endpoint to support application update of status and status description
- PUT endpoint triggers emails/notifications to respective parties if a change has been made
- Created new email HTML template for approve/reject scenario
- Updated notification builder util
> IG-602 Approve/Reject DAR functionality including notifications and emails

- src/resources/auth/auth.route.js
- src/resources/user/user.model.js
- src/resources/user/user.repository.js
- Updated auth route to return teams as part of user auth object when authentication is challenged
- Added teams to user model so we can lift teams a user is associated with
- Updated user repository to return teams and remove any unnecessary fields
> IG-606 Updated user middleware to store users teams

- src/resources/publisher/publisher.controller.js
IG-606
Populates mainApplicant for publishers, needed for data access request dashboard.
> IG-606 Pull mainApplicant

- src/resources/stats/stats.router.js
Changes to stats code to speed it up
> Changes to stats code to speed it up

- src/resources/person/person.route.js
- src/resources/person/person.service.js
- src/resources/tool/data.model.js
Added sector, organisation, showOrganisation and tags.topics to person route/service.
> IG-533-Added-new-fields-for-person

- src/resources/datarequest/datarequest.controller.js
- src/resources/datarequest/datarequest.model.js
- src/resources/message/message.model.js
- src/resources/publisher/publisher.controller.js
- src/resources/utilities/emailGenerator.util.js
- src/resources/utilities/helper.util.js
**PR**
- Backend work to support the addition and removal of collaborators on a data access request
- Notifications and emails issued to added collaborators
- Notifications and email issued to remove collaborators
- All collaborators notified and emailed if a data access request's status changes (e.g. submitted, approved/rejected etc.)
**Solution**
- Updated DAR MongoDb schema to include an array of collaborators (authors) consisting of objectIds representing Gateway users.
- Added a user friendly project ID (projectId) which is the objectId capitalised and separated by hyphens every 4 characters.
- Extended the DAR PUT endpoint for updating an application to include adding or removing collaborators based on new array passed in body.
- Modified authentication protocols on …
> Enabling add/remove collaborators on DAR with notifications and emails

- src/config/server.js
- src/resources/team/team.controller.js
- src/resources/team/team.route.js
**PR**
Endpoint to extract reviewers from a specified team for type ahead
**Solution**
- Created new 'teams' route
- Created endpoint to return team details by team ID
- Created endpoint to return team members by team ID
Both endpoints are secured by logged in user and the requesting user must be a member of the team requested.
> IG-771 - Endpoint to return team members for a given team

- src/resources/datarequest/datarequest.model.js
- src/resources/publisher/publisher.controller.js
- src/resources/team/team.controller.js
- src/resources/utilities/helper.util.js
- src/resources/workflow/workflow.controller.js
- src/resources/workflow/workflow.model.js
- src/resources/workflow/workflow.route.js
**PR**
Add CRUD endpoints for creating new workflow definitions, edit existing workflows that are not in use (no active applications) and delete workflows that are not in use.
**Solution**
- Updated DAR model to include reference to workflow definition by _id, also includes workflow object mapped to the workflow definition schema for storing a static version of the workflow attached
- Added endpoint to get all workflows for a publisher
- Added generic team function to detect if a user is in a given role for a given team
- Added create, edit, delete endpoints for workflows
- Added workflow model with separate workflow and step schemas for nested validation rules
> IG-770 - Endpoints for Add/Edit/Delete workflow definitions

- src/resources/bpmnworkflow/bpmnworkflow.controller.js
- src/resources/datarequest/datarequest.controller.js
- src/resources/datarequest/datarequest.model.js
- src/resources/datarequest/datarequest.route.js
- src/resources/publisher/publisher.controller.js
- src/resources/team/team.controller.js
- src/resources/topic/topic.controller.js
- src/resources/workflow/workflow.controller.js
- src/resources/workflow/workflow.model.js
**PR**
Add functionality to allow a workflow to be assigned to a DAR application
**Solution**
- Updated Camunda BPMN Workflow controller with correct URLs and aligned payloads
- Added new DAR PUT route for assigning workflow to a DAR
- Added assign workflow method to DAR controller
- Updated DAR model to accommodate attached workflow structure and progress per step
- Added reusable function in Workflow controller to calculate deadline SLA for Camunda
> IG-746 - Assigning a workflow to a data access request application

- src/resources/bpmnworkflow/bpmnworkflow.controller.js
- src/resources/datarequest/datarequest.controller.js
- src/resources/datarequest/datarequest.route.js
- src/resources/workflow/workflow.controller.js
- src/resources/workflow/workflow.model.js
**PR**
Add functionality to allow voting to take place on DAR with assigned complex workflows
**Solution**
- Added endpoint for accepting a vote from a reviewer to DAR controller
**To Do**
- Add endpoint to return current voting/recommendation data to populate modal
> IG-746 - Endpoint to allow voting on a complex workflow including Camunda integration

- src/resources/datarequest/datarequest.controller.js
**Added additional outputs**
- Loading voting/recommendation status to avoid user lookups
- Added deadlinePassed variable to instruct when phase deadline has elapsed for frontend styling
> IG-747 - Additional output for DAR workflow progress

- src/resources/datarequest/datarequest.controller.js
- src/resources/project/project.route.js
- src/resources/tool/tool.route.js
**PR**
Extend DAR about application step to allow selection of relatedNCS project.
**Solution**
- Added generic endpoint to tools route to allow the extraction of any entity type via a tag search parameter
- PR also includes supporting work for DAR modal voting display
**Note - vast majority of this is reformatting.  New function added to the tool.route file on lines 396 - 434.**
> IG-795 - Add endpoint to extract NCS projects

- .gitignore
- package.json
- src/config/server.js
- src/resources/datarequest/datarequest.controller.js
- src/resources/datarequest/datarequest.model.js
- src/resources/datarequest/datarequest.route.js
- src/resources/utilities/cloudStorage.util.js
IG-830[API for receiving files - Ability to upload/download files](https://hdruk.atlassian.net/browse/IG-829?atlOrigin=eyJpIjoiNWVjMWM5NzFiNzdlNGRhN2I3MmE0Mjg2NmFiZmI4OGMiLCJwIjoiaiJ9)
New additional cloudStorage.util file to manage files between express and cloud storage. [Multer](https://github.com/expressjs/multer#readme) handes multi/form-data for files as part of middleware. Updates to getting accessrequest and the owner of each file using populate. 
**Note** Can look at imporving the return of all files, it has been called again and the full update of the request for files has been returned as this has the user firstname and last name needed for the front.
> IG-830 Upload files

- src/config/configuration.js
- src/resources/auth/auth.route.js
- src/resources/datarequest/datarequest.controller.js
- src/resources/message/message.model.js
- src/resources/publisher/publisher.controller.js
- src/resources/team/team.controller.js
- src/resources/team/team.model.js
- src/resources/team/team.route.js
- src/resources/user/user.model.js
- src/resources/utilities/emailGenerator.util.js
- src/resources/workflow/workflow.controller.js
> Ig 708 robin

- src/resources/dataset/dataset.service.js
- src/resources/stats/stats.router.js
- src/resources/tool/data.model.js
Check in of code for datasets v2 and updates to course stats
> Check in of code for datasets v2 and updates to course stats

- src/resources/datarequest/datarequest.controller.js
Re-added fix to check for undefined publisher when submitting DAR to custodian who is not onboarded to Gateway
> SUPP-257 - Re-added fix to check for undefined publisher

- src/resources/datarequest/datarequest.controller.js
- src/resources/utilities/emailGenerator.util.js
**PR**
Attach .json representation of the email payload supplied to custodians on submission of a DAR application to provide a 'dirty' integration for custodians who will continue to use their own systems for managing requests.
**Solution**
- Extended email generation function to export json along with html body, included DAR unique identifier.
- Converted json directly into Base64 encoded string to attach to the SendGrid email using memory buffer rather than the filesystem alternative of saving to server directory to then attach the file.
- Updated email builder to support attachments.
- Attached the json to the email using the friendly unique ID for the DAR concatenated with the current date time for filename.
> IG-989 - Add json output attachment to email to custodian

- src/resources/datarequest/datarequest.controller.js
- Prevent patch update changing anything except question answers when the application has been submitted
> Prevented post submission updates to anything other than question answers

- package.json
- src/resources/datarequest/datarequest.controller.js
- src/resources/datarequest/datarequest.route.js
- src/resources/utilities/constants.util.js
- src/resources/utilities/dynamicForms/__mocks__/formSchema.js
- src/resources/utilities/dynamicForms/__tests__/dynamicForm.util.test.js
- src/resources/utilities/dynamicForms/dynamicForm.util.js
- src/resources/utilities/emailGenerator.util.js
- Added action endpoint to DAR to trigger different form actions as defined in the schema.  e.g. addRepeatableSection
- Added unit tests to support computation when modifying DAR schema
> IG-1096 - DAR repeatable form sections generic solution

- src/resources/datarequest/datarequest.controller.js
- src/resources/datarequest/datarequest.model.js
- Added schema identifier to DAR access records to allow reporting to distinguish between short form and 5 Safes
> Hot fix - DAR - Added tracking for schema type

- src/resources/datarequest/datarequest.controller.js
- src/resources/datarequest/datarequest.model.js
- src/resources/stats/stats.router.js
- Fix to resolve inflation of DAR stats after production data update and deprecation of datasetid field
> SUPP-351 DAR Homepage stats inflated

- src/resources/datarequest/datarequest.controller.js
- Removed backward compatibility code causing duplicate DARs in dashboard
- Datasetid field is now deprecated, all DARs can be derived from datasetids array going forward
> Fix - Removed backward compatibility code causing duplicate DARs in dashboard

- src/resources/datarequest/datarequest.controller.js
- Removed backward compatibility code causing duplicate DARs in dashboard
- Datasetid field is now deprecated, all DARs can be derived from datasetids array going forward
> Hot fix - Removed backward compatibility code causing duplicate DARs in dashboard

- src/resources/datarequest/datarequest.controller.js
- Modified DAR creation endpoint to include dataset titles as an array if created from a message concerning multiple datasets
- Modified DAR patch endpoint to include updated dataset titles if the applicant has changed their dataset selection
> IG-1228 - Reporting - Updated DAR creation to capture dataset titles applied for in document root

- src/resources/datarequest/datarequest.controller.js
- src/resources/datarequest/datarequest.route.js
Constraints:
- Only an applicant can delete a file.
- A file can be deleted only if the DAR is in pre-submission status.
- This is a soft delete, so the file won't be deleted from the bucket.
> Adding an API to soft delete a file from a data access request

- src/resources/dataset/dataset.route.js
SUPP 403 - Adding in lookup for courses when calling a dataset
> SUPP 403 - Adding in lookup for courses when calling a dataset

- src/config/server.js
- src/resources/search/search.repository.js
Fix for courses - switching the match to the beginning of the pipeline.
Commenting out code for requiring secure cookies when calling the api application.
> Fix for courses - switching the match to the beginning of the pipeline.

- src/resources/paper/paper.route.js
- src/resources/tool/data.repository.js
Handling structure where document_links is stored as array with objects within it.
> Handling retro structure of document_links for papers

- src/config/server.js
- src/resources/dataset/v1/dataset.route.js
- src/resources/dataset/v1/dataset.service.js
- Updated Sentry initialisation
- Added error trigger for testing on published environments
> IG-1357 - Updated Sentry initialisation and cache job entry point

- src/config/server.js
- src/resources/utilities/helper.util.js
Extended Sentry config to support all environments
> Extended Sentry config

- src/config/server.js
- src/resources/utilities/helper.util.js
Update to Sentry to fix alert/notification issues
> Sentry environment configuration

- src/resources/dataset/dataset.model.js
- src/resources/dataset/v1/dataset.service.js
- src/resources/tool/data.model.js
- Added new source field to dataset (v2) and tool model
- Populated updates and dataset creations in cache job with HDRUK MDC source
- Restructured technical details import code
- Reinstated console error logged to inform stackdriver of issues
> IG-1357 - Updated cache for stability based on Sentry feedback

- src/resources/base/repository.js
- src/resources/dataset/__tests__/dataset.controller.test.js
- src/resources/dataset/dataset.controller.js
- src/resources/dataset/dataset.model.js
- src/resources/dataset/v1/dataset.service.js
- src/resources/tool/data.model.js
- Added population operation to base repository
- Added is5Safes flag to dataset model
- Updated cache job to add is5Safes to all dataset entities
> IG-1439 - API updates to support cloning - GET operation for datasets

- src/resources/datarequest/datarequest.controller.js
- src/resources/publisher/publisher.controller.js
Requirement to be able to query a user's DAR applications by status for cloning.
- Added query optimisation for DAR dashboards for both applicants and custodians
- Added query parameter spread into DAR GET API to allow 'applicationStatus:inProgress' to be specified as a query string
> IG-1438 - Add queryable application status to DAR dashboard GET endpoint

- src/resources/stats/kpis.router.js
- Refactored stat queries
- Added KPI try catch to handle errors
- Fixed incorrect usage of createdAt variable instead of dateSubmitted for calculating new data access requests per month
- Updated javascript methods to MongoDb methods for query aggregation
> IG-1346 - Refactored KPI API

- src/resources/account/account.route.js
- src/resources/collections/collections.repository.js
- src/resources/collections/collections.route.js
[IG-1321](https://hdruk.atlassian.net/browse/IG-1321)
Additional apis for the collections dashboard, updated to be similar to other entity types
> IG-1321 additional apis for collections dashboard

- src/resources/datarequest/datarequest.controller.js
- src/resources/message/message.model.js
- src/resources/utilities/notificationBuilder.js
SUPP-443
To support the FE for navigating and missing Start review process.
- Update to message.model
- Update to API for send back message type
> Supp 443 - Application Status

- src/resources/datarequest/datarequest.controller.js
- src/resources/datarequest/utils/datarequest.util.js
- src/resources/dataset/v1/dataset.route.js
- src/resources/dataset/v1/dataset.service.js
- src/resources/utilities/constants.util.js
- src/resources/utilities/dynamicForms/dynamicForm.util.js
Updates to cloning functionality to include repeated sections with application forms.
- Fixed bug/poor performance in using findOneAndUpdate call when creating a new form from an existing form
- Added new functions to detect and copy repeating form sections
- Reinstated dataset cache job trigger
> IG-1509 - Data Access Request Cloning v2 - Includes repeated sections

- src/resources/datarequest/datarequest.controller.js
- src/resources/datarequest/datarequest.route.js
- src/resources/utilities/constants.util.js
- src/resources/utilities/emailGenerator.util.js
[IG-1515](https://hdruk.atlassian.net/browse/IG-1515)
> IG-1515 delete draft application API

- src/resources/datarequest/datarequest.model.js
- src/resources/datarequest/utils/datarequest.util.js
Fix for bug arising when amendment iterations are not provided with a default value when application is created from cloning operation.
> DAR - Cloning backend fix for amendment iterations

- src/resources/relatedobjects/relatedobjects.route.js
See https://github.com/HDRUK/gateway-web/pull/539
> Linked datasets should match title not URL

- src/config/server.js
- src/resources/linkchecker/linkchecker.router.js
- src/resources/utilities/emailGenerator.util.js
- Added failure callback for SendGrid integrations with Sentry notified
- Added release version to Sentry initialisation
> Sentry fixes

- src/resources/auth/auth.route.js
- src/resources/team/team.controller.js
- src/resources/team/team.model.js
- src/resources/team/team.route.js
- src/resources/utilities/constants.util.js
[IG-1668](https://hdruk.atlassian.net/browse/IG-1668) PUT and GET for Team notifications
This PR support IG-1413 FE which incorporates the backend logic for updating team notifications within the team dashboard and retrieving the list of notifications.
- New PUT API /api/v1/teams/{teamId}/notifications, handles updating team notifications
- NEW GET API /api/v1/teams/{teamId}/notifications, handles the retrieving of notifications
> IG-1668 Team Notifications API PUT / GET

- src/resources/stats/stats.router.js
Only bringing back the data that is needed for data access requests
> SUPP-472 - Site down

- src/resources/stats/stats.router.js
Only bringing back the data that is needed for data access requests
> SUPP-472 - Site down - dev checkin

- src/resources/datarequest/datarequest.controller.js
- src/resources/team/team.controller.js
[IG-1634](https://hdruk.atlassian.net/browse/IG-1634?atlOrigin=eyJpIjoiNTc3MGU4ZTA5ZDY3NGIwMWJjNWQ4ZTdhNzg3N2M3ZTEiLCJwIjoiaiJ9) Update email logic for pre-submission DAR's to include extra notification logic
- Create new logic to check for generic notifications within the team
- Find notification by type within the team and pull out generic emails
- Check custodian managers optIn status within the team.members and exclude or include based on optIn
- Merge of two emails lists 
- Send email notification to the combined list of emails
> IG-1634  Pre Submission DAR's extra email logic

- src/resources/search/search.repository.js
[IG-1680](https://hdruk.atlassian.net/browse/IG-1680)
> IG-1680 Add sorting by latest update in search API for people

- src/resources/account/account.route.js
- src/resources/course/course.repository.js
- src/resources/message/message.controller.js
- src/resources/tool/data.repository.js
- src/resources/tool/v1/tool.route.js
[IG-1721](https://hdruk.atlassian.net/browse/IG-1721)
> IG-1721 Remove unsubscribe link from existing gateway emails

- src/resources/message/message.controller.js
- src/resources/team/team.controller.js
- src/resources/utilities/emailGenerator.util.js
IG-1557 Epic
Additional check for disabled optIn for team notifications as manager. This to ensure emails render correctly with consistent text.
> IG-1557 Payload check for disabled team notifications

- src/resources/message/message.controller.js
Update for message controller and pulling out team from publisher
> Message controller update for team

- src/resources/dataset/datasetonboarding.controller.js
Issue was reported with team datasets dashboard loading slowly.  The query in place had a knock-on effect on the rest of the site, slowing things down due to the demand placed on the MongoDb instance.
1. Optimised query for datasets by reducing Db connections to 1 from (2n + 1) where n was the number of datasets returned
> Metadata Onboarding - Optimised team dashboard query

- src/resources/dataset/datasetonboarding.controller.js
An error has been reported when users attempt to create a new version of a dataset when metadata onboarding.
1. Added console.error commands to enable better problem tracking
2. Added missing JSON parse to interpret database stored question answers (string).
> SUPP-506 - Metadata Onboarding

- src/resources/dataset/datasetonboarding.controller.js
An error has been reported when users attempt to create a new version of a dataset when metadata onboarding.
1. Added console.error commands to enable better problem tracking
2. Added missing JSON parse to interpret database stored question answers (string).
> SUPP-506 - Metadata Onboarding - Fix for creating new version

- src/resources/search/search.repository.js
[IG-1677](https://hdruk.atlassian.net/browse/IG-1677)
- Update latest sort for dataset to use 'timestamps.updated'
- Add related resources sort for datasets
> IG-1677 latest update and related resources added for dataset sort

- package.json
- src/config/server.js
- src/resources/datarequest/datarequest.route.js
- src/resources/utilities/constants.util.js
- src/resources/utilities/logger.js
1. Updated to latest version of Sentry for API
> Sentry Issues

- src/services/mailchimp/mailchimp.js
Prevention of instantiation of MailChimp client in lower environments which do not have assigned API keys.
> IG-1722 - MailChimp Integration - Added check for api key before instantiating MailChimp client

- cloudbuild.yaml
- migrations/1620418612003-test_migration.js
- migrations/migrate.js
- package.json
- src/config/db.js
As development progresses on the Gateway, increasingly, data migrations are required as part of our deployment/release process.  Data migrations should be automatic and completed at the point of release to ensure maximum compatibility at all times and reduce the need for backward compatibility code.  Additionally, database updates, especially to production should be recorded, peer reviewed, consistent and if possible, reversible.
Initial commit for implementing automatic database migrations on promotion of code.
1. Added mongoose-migration npm package for migration process - https://www.npmjs.com/package/migrate-mongoose
2. Added sample migration file which will log a message during the merge to latest
3. Added ES6 compatible entry point to trigger migration scripts
4. …
> Database Migration Scripts - Setup

- src/services/mailchimp/mailchimp.js
Modified MailChimp export API to dispatch only subscribed users for a specific audience/marketing opt-in.
Implemented chunking to call MailChimp API will a max of 100 records at a time.
> MailChimp Integration Two Way Sync Update

- src/resources/dataset/v1/dataset.service.js
Fix mini cache commercial use filter
> Fix mini cache commercial use filter

- src/resources/utilities/emailGenerator.util.js
Attribution policy at the end "We ask that...."
> Added Gateway attribution policy into DAR submitted emails

- src/resources/topic/topic.controller.js
- src/resources/topic/topic.model.js
[IG-1941](https://hdruk.atlassian.net/browse/IG-1941)
> added is5Safes flag to topic when created

- migrations/1623235509532-authors_uploaders.js
[https://hdruk.atlassian.net/browse/IG-1961](https://hdruk.atlassian.net/browse/IG-1961)
> New migration script to add uploader to the list of authors

- migrations/1620558117918-applications_versioning.js
- src/resources/datarequest/amendment/amendment.controller.js
- src/resources/datarequest/amendment/amendment.service.js
- src/resources/datarequest/datarequest.controller.js
- src/resources/datarequest/datarequest.entity.js
- src/resources/datarequest/datarequest.model.js
- src/resources/datarequest/datarequest.repository.js
- src/resources/datarequest/datarequest.route.js
- src/resources/datarequest/datarequest.service.js
- src/resources/datarequest/utils/datarequest.util.js
- src/resources/filters/filters.mapper.js
- src/resources/publisher/publisher.controller.js
- src/resources/publisher/publisher.repository.js
- src/resources/utilities/constants.util.js
Updates to selection of versioning to support major versions and fixes for minor versioning
- Continued major versioning development and build out
- Refactored and reworked minor versioning
> IG-1919 - DAR - Versioning/Amend

- migrations/1623322905323-5safes_nhsd_removal.js
[IG-2012](https://hdruk.atlassian.net/browse/IG-2012)
> IG-2012 Added script to remove 5Safes for NHSD

- src/resources/datarequest/datarequest.controller.js
- src/resources/datarequest/datarequest.entity.js
- src/resources/datarequest/datarequest.service.js
- src/resources/publisher/publisher.controller.js
- Updated delete draft function to keep other major versions in sync so the deleted version cannot be selected
- Adding tracking of application status within each major version in the version tree to allow hiding of major versions in presubmission status from custodian users
> IG-1919 - Amend - Updated Delete Draft and Custodian Version Exposure

- src/resources/datarequest/datarequest.service.js
Change amend logic to create a new major version in submitted status instead of in review.
- Updated create amendment logic to set application status to submitted instead of in review and remove Camunda linkage.
> DAR - Update Amend logic to start at submitted status instead of in review

- src/resources/stats/stats.repository.js
[IG-2006](https://hdruk.atlassian.net/browse/IG-2006)
- Return only active entities
- Return counter with no aggregation applied
> IG-2006 Updates to popular entities api

- migrations/1622731580031-first_message_is5safes.js
- src/resources/topic/topic.model.js
Due to the incoming changes of the enquiry journey, a data migration is required to update existing messages so they can flow in the same way.
- Data update to treat existing messages based on the recipient custodian 5 safes status.  Added 'is5Safes' property to each relevant topic in database.
> MERGE FOR JULY RELEASE - IG- Added migration script for is5Safes to topics

- security-vulnerability-discloure-policy.md
- security.txt
Added security and vulnerability disclosure policy
> Adding  security and vulnerability disclosure policy

- src/resources/datarequest/amendment/amendment.controller.js
- src/resources/datarequest/amendment/amendment.service.js
- src/resources/datarequest/datarequest.controller.js
- src/resources/datarequest/datarequest.model.js
- src/resources/datarequest/datarequest.repository.js
- src/resources/datarequest/datarequest.service.js
- src/resources/utilities/constants.util.js
- src/resources/utilities/emailGenerator.util.js
Completion of amend feature including highlighting of answers changing between major versions
- Backend highlighting of changes/amendments in a new major version
- Email updates to list only changes made to an application when resubmitted with amendments
> DAR - Amend - IG-1921 + IG-2021

- src/resources/dataset/datasetonboarding.controller.js
- src/resources/dataset/datasetonboarding.route.js
[IG-2049](https://hdruk.atlassian.net/browse/IG-2049)
Added a new endpoint to delete a draft dataset using its object id
> IG-2049 Endpoint to delete draft added

- src/resources/dataset/datasetonboarding.controller.js
- src/resources/message/message.model.js
- src/resources/utilities/emailGenerator.util.js
[IG-2050](https://hdruk.atlassian.net/browse/IG-2050)
> IG-2050 Adding in notifications and emails for delete draft dataset

- src/config/server.js
- src/resources/activitylog/activitylog.controller.js
- src/resources/activitylog/activitylog.model.js
- src/resources/activitylog/activitylog.repository.js
- src/resources/activitylog/activitylog.route.js
- src/resources/activitylog/activitylog.service.js
- src/resources/activitylog/dependency.js
- src/resources/datarequest/datarequest.controller.js
- src/resources/datarequest/datarequest.repository.js
- src/resources/datarequest/datarequest.route.js
- src/resources/datarequest/datarequest.service.js
- src/resources/datarequest/dependency.js
- src/resources/datarequest/utils/datarequest.util.js
- src/resources/utilities/constants.util.js
Creation of GET API for retrieving logs relating to multiple versions of a Data Access Request.
1. Added V2 repo pattern setup for activity log resource including new route for GET endpoint
2. Updated Activity Log model with enumerators for event and log types
3. Added middleware to validate and authorise log requests
4. Added formatted output for logs from GET endpoint
**Work remaining**
1. The metric for 'time with applicants' is scheduled for delivery in a later ticket/sprint, this is currently hardcoded to 100%.
> IG-1999 - DAR - Activity Log GET API

- src/resources/activitylog/activitylog.service.js
- src/resources/datarequest/datarequest.controller.js
- src/resources/utilities/constants.util.js
[IG-2131](https://hdruk.atlassian.net/browse/IG-2131)
> Add application related activity logs

- src/resources/dataset/datasetonboarding.controller.js
- src/resources/utilities/emailGenerator.util.js
[IG-1893](https://hdruk.atlassian.net/browse/IG-1893)
> IG-1893 Updates to rejected dataset email

- src/resources/dataset/datasetonboarding.controller.js
- src/resources/utilities/emailGenerator.util.js
[IG-1894](https://hdruk.atlassian.net/browse/IG-1894)
> IG-1894 Copy change to delete draft email and notification

- src/resources/activitylog/activitylog.controller.js
- src/resources/activitylog/activitylog.repository.js
- src/resources/activitylog/activitylog.route.js
- src/resources/activitylog/activitylog.service.js
- src/resources/datarequest/datarequest.entity.js
- src/resources/datarequest/datarequest.repository.js
- src/resources/datarequest/datarequest.service.js
- src/resources/datarequest/utils/datarequest.util.js
- src/resources/message/message.controller.js
- src/resources/message/message.model.js
- src/resources/team/team.controller.js
- src/resources/topic/topic.model.js
- src/resources/utilities/constants.util.js
- src/resources/utilities/emailGenerator.util.js
**Requirement**
Backend implementation required to allow the creation of manual events and association to a specified application version activity log.
- Added create log endpoint controller logic with associated route, middleware and email generation.
- Added delete log endpoint controller logic with associated route, middleware and email generation.
- Renamed branched 'createdByUserType' property in message topic to match contextual messaging feature branch naming 'userType'
- Updated message model to include new in-app notification type for activity log changed
> IG-2002 - DAR - Activity Log - Manual Event Creation and Deletion

- src/config/server.js
- src/resources/cohortprofiling/cohortprofiling.controller.js
- src/resources/cohortprofiling/cohortprofiling.model.js
- src/resources/cohortprofiling/cohortprofiling.repository.js
- src/resources/cohortprofiling/cohortprofiling.route.js
- src/resources/cohortprofiling/cohortprofiling.service.js
Model and query change due to new structure of white rabbit data.
Added POST route for saving and transforming cohort profiling json files.
> Added cohort profiling POST and amended cohort profiling GET

- src/config/server.js
- src/resources/global/dependency.js
- src/resources/global/global.controller.js
- src/resources/global/global.model.js
- src/resources/global/global.repository.js
- src/resources/global/global.route.js
- src/resources/global/global.service.js
Creation of a new GET endpoint to retrieve the data mapping reference data for data utility wizard
- Created repository pattern API for global data which can return data utility for a specific language e.g. {baseUrl}/api/v1/global?localeId=en-gb&entry.name=dataUtility
- Added new route as above to server config
> IG-2166 - GET endpoint for retrieving Data Utility from global data collection

- package.json
- plop-templates/repositoryPattern/controller.hbs
- plop-templates/repositoryPattern/dependency.hbs
- plop-templates/repositoryPattern/entity.hbs
- plop-templates/repositoryPattern/model.hbs
- plop-templates/repositoryPattern/repository.hbs
- plop-templates/repositoryPattern/route.hbs
- plop-templates/repositoryPattern/service.hbs
- plopfile.js
- src/config/server.js
In order to speed up the creation of new entities and associated CRUD functions, this introduces Plop, a code generation framework in combination with HandleBars, a code templating tool.  Using these tools, we can automate the creation of a skeleton repository pattern for a new entity.
- Added plop profile configuration file
- Added template files for all repository pattern modules
This tool can be run using 
`plop repositoryPattern {entityName}`
To install Plop globally, use
`npm install -g plop`
Please note you may need to use 'sudo' prefix if installing globally.
> Code generation framework (Plop + Handlebars)

- src/resources/datarequest/datarequest.controller.js
- src/resources/datarequest/datarequest.entity.js
- src/resources/datarequest/datarequest.repository.js
Correction for issues experienced in file upload for Data Access Request applications where the file upload status was not being correctly returned and saved to the database once the scanning service had completed.  This meant that files were uploading correctly, but could not be downloaded again.
- Fixed syntax and asynchronous errors in endpoint that is called by scanning service upon scan completion
- Fixed 401 permissions issue for users trying to delete uploaded files by including required database fields in repository query used by the controller's field delete method
> SUPP-663 - DAR - Fixed file upload issues with versioning

- migrations/1627566998386-add_globals.js
[https://hdruk.atlassian.net/browse/IG-2170](IG-2170)
> Add step 6 in the data utility wizard

- src/resources/datarequest/amendment/amendment.controller.js
[ICODARA-122](https://hdruk.atlassian.net/browse/ICODARA-122)
> fix request update warning for dynamically generated questions

- src/resources/cohort/cohort.model.js
[IG-2239](https://hdruk.atlassian.net/browse/IG-2239)
> IG-2239 renamed 'status' to 'activeflag' in line with other entities

- src/config/server.js
- src/resources/dataUseRegister/dataUseRegister.controller.js
- src/resources/dataUseRegister/dataUseRegister.entity.js
- src/resources/dataUseRegister/dataUseRegister.model.js
- src/resources/dataUseRegister/dataUseRegister.repository.js
- src/resources/dataUseRegister/dataUseRegister.route.js
- src/resources/dataUseRegister/dataUseRegister.service.js
- src/resources/dataUseRegister/dependency.js
- src/resources/utilities/constants.util.js
[IG-2267](https://hdruk.atlassian.net/browse/IG-2267)
> Add get and patch API for data use register

- src/resources/datarequest/datarequest.controller.js
**Support ticket description** 
'When someone submits updates to data access request, a notification email is sent to the custodian. This is the current message subject line in the email: 'Data Access Request to OTHER > HEALTH DATA RESEARCH UK for HDR UK Papers & Preprints has been updated with updates'. Please remove 'with updates' at the end of the sentence. Thanks'
- Updated email subject to requested copy.
> SUPP-640 - DAR email copy update for submitted updates 

- src/resources/cohort/cohort.model.js
[IG-2182](https://hdruk.atlassian.net/browse/IG-2182)
- Added type and related objects
- Changed 'isPublic' to 'publicflag' in line with existing flag
> IG-2182 Changes to cohort model

- src/resources/auth/strategies/azure.js
Fix for allowing HTTPS redirect URLs
> CR - including proxy to allow for HTTPS in Axure strategy

- src/resources/dataUseRegister/dataUseRegister.controller.js
- src/resources/dataUseRegister/dataUseRegister.repository.js
- src/resources/dataUseRegister/dataUseRegister.route.js
- src/resources/dataUseRegister/dataUseRegister.service.js
- src/resources/dataUseRegister/dataUseRegister.util.js
- src/resources/search/search.repository.js
- src/resources/utilities/emailGenerator.util.js
Add a new endpoint to implement a search API for DUR
> Add search data use register API

- src/resources/cohort/__mocks__/cohorts.js
- src/resources/cohort/__tests__/cohort.service.test.js
- src/resources/cohort/cohort.model.js
- src/resources/cohort/cohort.service.js
- src/resources/cohort/dependency.js
- src/resources/dataset/dataset.service.js
Work completed:
Added logic to addCohort to allow surfacing translated OMOP descriptor. 
Updated addCohort test to reflect new data structure sent from RQuest.
Removed updatedAt field from model and service
BCP have changed the structure of the incoming payload from RQuest.  To get the English readable OMOP names we need to do a look up on an array which they have passed in the payload (**_query_codes_**).  In our code the lookup will be handled by the **_appendTranslatedOMOPDescriptions()_** function which will append the translated OMOP descriptor to the **_rules_** array (the array we were expecting the translated value to be in in the first place).  This will mean minimal front-end changes are required. 
Subset of new payload below:
```
"cohort": {     
"input": {           
"cohorts" …
```
> Refactored addCohort to use services. Added test

- src/resources/publisher/publisher.model.js
[IG-2556](https://hdruk.atlassian.net/browse/IG-2556)
> IG-2556 wordTemplate field added to publisher model

- jest.config.js
- src/resources/search/filter.route.js
- src/resources/search/util/__tests__/search.util.data.js
- src/resources/search/util/__tests__/search.util.test.js
- src/resources/search/util/search.util.js
```
https://hdruk.atlassian.net/browse/GAT-400
```
> array to tree

- src/services/aridhia/aridhia.controller.js
This additional code to the script make sure to delete deprecated datasets from the database.
> the script removes deprecated datasets

- Dockerfile.dev
- jest.config.js
- src/resources/search/filter.route.js
- src/resources/search/util/__tests__/search.util.data.js
- src/resources/search/util/__tests__/search.util.test.js
- src/resources/search/util/search.util.js
main story
```
https://hdruk.atlassian.net/browse/GAT-265
```
> spatial filter: convert array to tree 

- Dockerfile.dev
- jest.config.js
- src/resources/search/filter.route.js
- src/resources/search/util/__tests__/search.util.data.js
- src/resources/search/util/__tests__/search.util.test.js
- src/resources/search/util/search.util.js
main story:
```
https://hdruk.atlassian.net/browse/GAT-265
```
> add docker file for dev

- src/resources/dataUseRegister/dataUseRegister.service.js
- src/resources/dataUseRegister/dependency.js
- src/resources/datarequest/datarequest.controller.js
Bug fixes for mapping between DAR and DUR (473) and automatic email when DUR is created from an approved DAR.
> GAT-473 and GAT-475 bug fixes

- src/resources/search/filter.route.js
Fixes a bug where the filters list on the FE appears greyed out when it shouldn't be
> release-fix/GAT-611

- docs/index.docs.js
- docs/resources/spatialfilter.docs.js
update api-docs with details about spatial filter
> added spatial filter in api-docs

- src/resources/base/repository.js
- src/resources/filters/filters.service.js
```
https://hdruk.atlassian.net/browse/GAT-684
```
> Releasefix GAT 684 update buildfilters

- src/resources/datarequest/datarequest.controller.js
Fixes a bug where the DURs which are created automatically from an approved DAR were being created twice because of a defect in the code.
> bug/GAT-810-SUPP-968 - remove duplicate DUR bug

- src/resources/datarequest/datarequest.controller.js
Fixes a bug where the DURs which are created automatically from an approved DAR were being created twice because of a defect in the code.
> bug/GAT-810-SUPP-968-bau - fix DUR duplicate bug

- src/controllers/datasetonboarding.controller.js
Release fix/gat 919 - reject dataset broken
> Release fix/gat 919 - reject dataset broken

- src/middlewares/__tests__/dataUseRegister.middleware.test.js
- src/middlewares/dataUseRegister.middleware.js
Fixes the fix for editing DURs - previously was matching on wrong field
> GAT-928 - second attempt at fix

- src/resources/user/user.service.js
> autosuggest response

- src/resources/datarequest/schema/datarequest.schemas.model.js
- src/resources/questionbank/questionbank.service.js
Story/gat 1011 - support for unpublished icons
> Unpublished updates

- src/config/server.js
- src/resources/dataUseRegister/dataUseRegister.controller.js
- src/resources/search/__tests__/searchFilter.controller.test.js
- src/resources/search/search.repository.js
- src/resources/search/search.router.js
- src/resources/search/searchFilter.controller.js
- src/resources/search/searchFilter.route.js
- src/resources/utilities/constants.util.js
Updates the behaviour of the search filter to prevent filter options disappearing when select options within a given filter category e.g., publisher
> story/GAT-1103 - search filter behaviour

- src/resources/message/message.controller.js
Only send messages to PubSub if they are a valid UI user and not a service account, otherwise we end up in a feedback loop...
> Only send PubSub if not service account

- src/services/aridhia/aridhia.service.js
> read name from catalog.title

- src/resources/dataset/dataset.entity.js
> changed folder name from 'latest' to '2.1'

- src/resources/auth/utils.js
Added condition as per suggested in ticket
> updated auth error handling for Azure
