HDRUK/gateway-api

- src/resources/paper/paper.route.js
**PR**
Prevent users from adding the same paper twice
**Solution**
- Added paper endpoint api/v1/papers/validate which accepts "link" as a string.
- Endpoint returns an error if a direct matching link is found against an active or under review paper (link is trimmed of white space prior to comparison)
**Future**
- We could consider applying more validation to the URL field perhaps in the form of an input mask
> IG-349 - Detect duplicate paper links

- src/resources/message/message.controller.js
- src/resources/topic/topic.controller.js
- src/resources/topic/topic.model.js
**PR**
Allow messaging everywhere using sidedrawer within site and accommodate multiple datasets
**Solution**
- Made modifications to messaging APIs to support multiple datasets from single publisher
- Fixed defect in sort order so that unread messages are shown first, then sorted by date of the last unread message and finally by created date
**Future**
Messaging can be quite easily extended now to generate a new topic for each publisher when we need to accommodate messaging to multiple custodians/teams (but allow the user to send only a single message)
> IG-564 - Allow messaging everywhere in site and accommodate multiple datasets

- src/resources/publisher/publisher.controller.js
- src/resources/publisher/publisher.model.js
- src/resources/publisher/publisher.route.js
- src/resources/team/team.model.js
- src/resources/topic/topic.controller.js
**PR**
Add the ability to select multiple datasets during a data access request to a single custodian
**Solution (Branch WIP but stable with these commits)**
- Added publisher route and controller
- Added endpoint to retrieve all datasets for a publisher (used in multiselect)
- Updated publisher and team model to include unique numeric ID
**Next commits**
- Data persistence for multiple datasets when submitting and reloading Data Access Request forms
> IG-472 - Multiple datasets during Data Access Request

- src/resources/datarequest/datarequest.route.js
- src/resources/publisher/publisher.controller.js
- src/resources/publisher/publisher.route.js
**PR**
Backend work to support teams in account area.  This allows us to request all applications that are attached to any custodian by passing in the custodian name.  
Security is implemented such that a requesting user must be a member of the custodian team to get a valid response otherwise they will receive a 401.
**Solution**
- Added new endpoint to support requirements in publisher route.
> Added endpoint for returning DARs for any publisher

- src/resources/search/search.router.js
**PR**
Issues reported by users that searching for "Cog-uk" returned more results than expected.  This was down to the default behaviour of Mongo to remove hyphens and treat the above as 'contains Cog OR uk'.
**Solution**
- Regex added to detect search words that include a hyphen and replaces them with the original word wrapped in quotation marks.  Mongo then treats the original hyphenated as a phrase and performs 'contains Cog-uk'.
> Added phrase encapsulation for hyphenated words

- src/resources/publisher/publisher.route.js
This public endpoint only exposes the following info:
- publisher name
- publisher DAR pre-submission modal content
- publisher allows/does not allow messaging
None of this info is sensitive and is required for this page to operate properly when a user has not signed in yet. 
We will need to revisit this if the publisher data model is extended to include sensitive data.
> Fixed unauth issue by removing auth requirement on publisher endpoint

- src/resources/auth/auth.route.js
- src/resources/team/team.model.js
- src/resources/user/user.repository.js
**PR**
Extend teams to include roles including auth payload to UI
**Solution**
- Extended auth route to return desired payload to include a users roles within each team
_Main modifications from line 69 to 90 (reformatting affected whole file)_
- Extended team model to include an array of roles driven by enum (currently reviewer and manager only)
**Sample Payload**
`{
"role": "Admin",
"id": 6689395059831886,
"name": "Robin Kavanagh",
"loggedIn": true,
"teams": [
{
"_id": "5f3f98068af2ef61552e1d75",
"name": "ALLIANCE > BARTS",
"type": "publisher",
"roles": [
"reviewer"
]
},
{
"_id": "5f3ff10f78d7db8866a26fe7",
"name": "ALLIANCE > SAIL",
"type": "publisher",
"roles": [
"reviewer"
]
},
{
"_id": "5f58f23f55ae131f3ffacf11",
"name": "HDR UK",
"type": "publisher",
"roles": [
"reviewer"
]
}
]
}` …
> IG-740 + IG-744 - Adding users' team roles (manager/reviewer)

- src/resources/bpmnworkflow/bpmnworkflow.controller.js
- src/resources/datarequest/datarequest.controller.js
- src/resources/datarequest/datarequest.model.js
- src/resources/datarequest/datarequest.route.js
- src/resources/workflow/workflow.controller.js
- src/resources/workflow/workflow.model.js
**PR**
The DAR PUT endpoint should be extended to:
- Allow a manager to make a final decision before a workflow is assigned or when a phase is in progress.  
- A manager should also be able to end a phase with a single decision, ignoring all other voters.  
- A manager should also be able to make a final decision with workflow in progress.
**Solution**
- Added endpoint for start review (triggered by manager on submitted applications)
- Added endpoint to override an application workflow step 
- Updated associated workflow/step model to track completion state of each step and the start date/time of pre-review
> IG-745 + IG-751 Completed manager override capability for workflow phase or for entire workflow

- src/resources/datarequest/datarequest.controller.js
**PR**
The DAR emails aren't marketing emails, so no option should be provided for opting out of them.
Agreed during demo for Sprint 11 by David Seymour, Gerry Reilly, Peggy and Susheel.
**Solution**
Removed opt-in status check for email generations
Removed unsubscribe link from email body
> IG-791 - Removed subscribe link from DAR emails and negated opt-in status

- src/resources/datarequest/datarequest.controller.js
- src/resources/team/team.controller.js
**PR**
Email only managers on submission of DAR
**Solution**
- Modified email generation function to identify managers of the custodian team
- Ensured custodians who are not onboarded on the Gateway are emailed via the dataset contact point (except on dev/uat etc)
> IG-741 - Submission of DAR should email only Team Managers

- src/resources/auth/strategies/jwt.js
- src/resources/auth/utils.js
- src/resources/bpmnworkflow/bpmnworkflow.controller.js
- src/resources/user/user.roles.js
- src/resources/user/user.route.js
Add JWT auth to the camunda endpoints on the gateway-api. This is to allow secure and authenticated requests to be made. 
Added token generation to the auth utils for camunda. A username must be passed that exists within the camunda admin group.
> IG-804-Add-auth-for-Camunda

- src/resources/datarequest/datarequest.controller.js
- src/resources/datarequest/datarequest.model.js
- src/resources/publisher/publisher.controller.js
- src/resources/workflow/workflow.controller.js
- Changed MongoDb model for DAR to hold 'aboutApplication' as an object which is searchable for NCS
- Made existing DARs backward compatible by first parsing json if it is a string instead of an object
- Updates to existing DARs will now save 'aboutApplication' as objects
Tested new and existing DARs, working as expected.
> Changed aboutApplication from json string to object in MongoDb

- src/resources/datarequest/datarequest.controller.js
- src/resources/datarequest/datarequest.route.js
- src/resources/utilities/emailGenerator.util.js
- src/resources/workflow/workflow.controller.js
**PR**
Completion of the email generation to step reviewers when their review deadline is approaching and a separate email to managers when a deadline elapses.
**Solution**
- Completed DAR deadline notification endpoint
- Tested via Postman and Camunda
Still requires solution in Camunda to trigger the endpoint once a deadline timer passes.
> Completed DAR deadline emails

- src/resources/datarequest/datarequest.controller.js
- src/resources/datarequest/datarequest.model.js
- Creating a new DAR now associates the MongoDb objectId of the schema it was built from to the DAR document.  This allows us to query all DARs by a particular schema version including the ability to distinguish the enquiry short forms.
> IG-1120 - Added schema version tracking within DAR applications

- src/resources/paper/paper.route.js
- src/resources/project/project.route.js
- src/resources/tool/tool.route.js
[SUPP 339](https://hdruk.atlassian.net/browse/SUPP-339?atlOrigin=eyJpIjoiYzA0NjgyOGZmYzkzNDFjYTgwZGFiZDNlY2IxMjIwMDIiLCJwIjoiaiJ9)
An small issue was reported that the Uploader field within Tool, Projects and Papers was outputting the numeric user id based in tools > users. A solution has been implemented to declare a new field called **uploader** which concats **$uploaderIs** and selects out the users firstname and lastname
> SUP-339 - Project uploader shown as ID NOT name

- src/resources/datarequest/datarequest.controller.js
- src/resources/datarequest/datarequest.model.js
- src/resources/stats/stats.router.js
Deprecation of dataSetId field in Data Access Request model has been completed now that production data has been updated.
All previous dataSetId values are now stored in datasetIds array at position 0.
Stat calculation logic modified to count only DARs using the new array.  This fix prevents the inflation of DAR figures on the Gateway home page.
> DAR Stats - Inflating stats code fix for DAR submissions

- src/resources/utilities/__tests__/helper.util.test.js
- src/resources/utilities/helper.util.js
[SUPP-334](https://hdruk.atlassian.net/browse/SUPP-334?atlOrigin=eyJpIjoiYzY0MGVkNjc3MGI3NDcxYWFiZDk4NzAzZDBiYTI5ZGUiLCJwIjoiaiJ9)
Reported that issues occured when updating tools and projects and specifically emails. This was due to the censorship being applied to those emails if the user was not a custodian. A check has now been put in place within the **helper.util** file to allow email address to be processed with 1-2 characters. Tests have also been added to validate the fix.
> SUPP-334 Validate against short email

- src/config/server.js
- src/resources/auth/auth.route.js
- src/resources/auth/sso/sso.discourse.router.js
- src/resources/auth/strategies/google.js
- src/resources/auth/strategies/linkedin.js
- src/resources/auth/strategies/oidc.js
- src/resources/user/user.register.route.js
- Added code to hide 'powered-by' from response headers
- Made all cookies issued by the Gateway HTTP only and secure when deployed to GCP
> IG-1775 - API Express Security Improvements

- src/resources/datarequest/datarequest.controller.js
- src/resources/utilities/emailGenerator.util.js
- Appended 'about application' details into DAR submission email that goes to the Custodian.  Now includes project name, and if the application is in relation to an NCS project.
- Added hyperlink to email body to go directly to the NCS project.
- Updated json payload to include 'about application' details in new object.
> SUPP-369 - On DAR submission, custodian emails do not contain NCS project details

- package.json
- src/config/server.js
- src/resources/auth/auth.route.js
- src/resources/auth/oauth.route.js
- src/resources/auth/strategies/jwt.js
- src/resources/auth/utils.js
- src/resources/user/user.model.js
- src/resources/user/user.repository.js
- src/resources/user/user.route.js
- src/resources/utilities/helper.util.js
This ticket introduces a method of authenticating application/clients against the Gateway by associating a team/custodian manager as a service account which is authorised through an OAuth2.0 client credentials flow.
The following work has been completed:
- Added OAuth authorisation route for issuing bearer tokens to client applications (client credentials grant type)
- Modified current security to allow jwt in cookie format and also now in 'Bearer {token}' format via HTTP authorisation request header
- Updated Mongoose schema for User model to include client id and secret as well as 'isServiceAccount' for filter purposes
- Added User repository method to find service accounts based on client credentials passed
- Added endpoint/route to allow Gateway admins to create service accounts for …
> IG-1077 - Third party integration and authorisation via OAuth2.0 client credentials

- src/resources/publisher/publisher.controller.js
- Modified MongoDb query to return only active instances of datasets.  This endpoint is used to provide data to the dataset multi-select component in the DAR about application section.
> SUPP-394 - DAR - Searching for other publisher datasets now only returns active datasets

- src/resources/tool/data.model.js
- src/resources/tool/data.repository.js
- src/resources/utilities/__tests__/urlValidator.test.js
- src/resources/utilities/urlValidator.js
**JIRA:** 
https://hdruk.atlassian.net/browse/IG-1265
**Description:** 
This ticket is the backend work to allow a user to save a paper with different URL link types (DOI, PDF & HTML).  After observing how the data had been loaded into Production (IG-697) and having a 3 amigos session on Friday 29th Jan it was decided that the best way to structure this data in the DB is as follows:
```
"document_links":
{
"pdf":["https://europepmc.org/articles/PMC7467523?pdf=render"],
"doi":["https://doi.org/10.1136/bmjresp-2020-000644"],
"html":["https://europepmc.org/articles/PMC7467523"]
}
```
The backend will determine whether or not a provided URL is a DOI link and then save the data accordingly.  It will **not** be able to determine whether a provided PDF URL is a valid PDF link.
> Added document_links to data model for papers

- swagger.yaml
Added highly detailed documentation for the following endpoints:
`POST /oauth/token`
For an application to request a bearer token to allow it to communicate with the Gateway under specific team/Custodian based client credentials.
`GET /api/v1/data-access-request/{id}`
To request the full details of a single application form by a given unique identifier.
`PUT /api/v1/data-access-request/{id}`
To update a single application form’s status using a given unique identifier and a specific request payload.  E.g. to ‘Approved’.
`GET /api/v1/publishers/{team}/dataaccessrequests`
To retrieve a collection of data access requests submitted to a publisher.
> IG-991 - Swagger doc update to DAR and corrected all syntax errors

- src/config/account.js
- src/config/configuration.js
- src/resources/auth/auth.route.js
- src/resources/user/user.model.js
- src/resources/user/user.route.js
Added new claim 'rquestroles' for OIDC which will be passed to BC Platforms to show that a user has been approved on the gateway for advanced search access.
Also see description in https://github.com/HDRUK/gateway-web/pull/463
> Backend logic for Cohort Discovery user validation

- src/resources/course/course.repository.js
- src/resources/tool/data.repository.js
Bug:
Same course (or other entity) appearing in multiple pages of the admin dashboard.
Steps to recreate:
Open your network tab and go to Courses dashboard on Production
Click on the API call in network tab, should look like this getList?status=active&offset=0
In Preview tab expand data and copy out all of the _id values in the response.
Paste these values into a tool to find duplicate values such as https://www.somacon.com/p568.php
Repeat this process for the other pages on courses and you should see some _id values appearing more than once.
Solution:
This was happening because multiple entities of the same type had the exact same value for their sort column (updatedAt).  I have now added _id as a tiebreaker column in the sort.
> Added second sort column to sort to fix entities dashboard bug

- swagger.yaml
Updated documents for the following endpoints for API v2:
GET https://api.{env}/api/v2/courses/{id}
GET https://api.{env}/api/v2/courses/
GET https://api.{env}/api/v2/papers/{id}
GET https://api.{env}api/v2/papers
GET https://api.{env}/api/v2/projects/{id}
GET https://api.{env}/api/v2/projects
GET https://api.{env}/api/v2/tools/{id}
GET https://api.{env}/api/v2/tools
GET https://api.{env}/api/v2/datasets/{id}
GET https://api.{env}/api/v2/datasets
> IG-1358 - Updated swagger docs for v2 entities

- src/resources/stats/stats.router.js
- Updated popular entity counter logic to group entities by type and name when counting their popularity, collapsing dataset versions together for correct aggregation returning only a single dataset with pid.
- Reduced response payload to minimal size for performance enhancement.
> SUPP-441 - Aggregate dataset versions for popular entities display

- src/resources/datarequest/amendment/amendment.controller.js
- src/resources/datarequest/datarequest.controller.js
- src/resources/datarequest/utils/__tests__/datarequest.util.test.js
- src/resources/datarequest/utils/datarequest.util.js
- src/resources/utilities/constants.util.js
Issue reported by HSCNI where the Custodian was able to click 'request update' on an application form at an incorrect point in the application process.  Clicking this button triggered an error response by the backend which was handled correctly.
- Updated object mapper that serves the correct action buttons in a variety of situations to also take into account the current active party viewing an application form that is in review status.
- Updated tests for functionality to include new parameter and new test case.
> SUPP-451 - DAR - Fix custodian actions buttons in review

- src/resources/team/team.controller.js
Extension of IG-1668 missing default email value
During demo prep we came across an issue for default values for notification emails being missing on inital load. An API update for the default value has been introduced to stop a rendering issue with the FE.
> IG-1668 Set default value for emails

- src/resources/datarequest/datarequest.model.js
- src/resources/datarequest/utils/datarequest.util.js
At the point of cloning an application, we need to store the unique identifier in the new application that is corrected, so that we can formulate a link back to the original application.
This will assist in building reporting capability around the usage of this function.
1. Updated Mongoose document for DAR to include a new object id called ‘originId’ or similar
2. Updated cloning endpoint to save _id of original document into the originId of the new application entity
> IG-1807 - DAR - Add origin application id to applications that are created via cloning

- src/resources/user/user.service.js
- src/resources/utilities/emailGenerator.util.js
[IG-1804](https://hdruk.atlassian.net/browse/IG-1804) main information is on [IG-1382](https://hdruk.atlassian.net/browse/IG-1382?atlOrigin=eyJpIjoiODgzNjZiZWUxOWE0NGE4MzhkM2U0NGQ4OGM2N2Y4NzYiLCJwIjoiaiJ9)
When a new user registers via the gateway we now send an introductory email to their email address to inform them of the services HDRUK provide. We use a sendgrid template to do this so HDRUK can control the look and feel at any time. The design document sits [here](https://hdruk.atlassian.net/wiki/spaces/IG/pages/1332936759/Introductory+email) currently. 
This is done at the point of creation within the user.service.js. Email is to come from enquiry@hdruk.ac.uk confirmed by Vicky.
- Requires new env variable to be inserted **SENDGRID_INTRO_EMAIL** for all environments
> IG-1804 Introduction email

- src/resources/dataset/dataset.model.js
- src/resources/dataset/datasetonboarding.controller.js
- src/resources/dataset/v1/dataset.service.js
- src/resources/filters/__mocks__/filters.mocks.js
- src/resources/filters/__tests__/filters.service.test.js
- src/resources/filters/filters.controller.js
- src/resources/filters/filters.mapper.js
- src/resources/filters/filters.repository.js
- src/resources/filters/filters.service.js
- src/resources/filters/utils/filters.util.js
- src/resources/tool/data.model.js
Commerical usage filter 
Commercial usage filter will allow researchers to search for datasets allowed for commercial use.
The filters will go in order of the following to compute commercial research.
-    A note on the filter to indicate that the commerical use is in beta use only it is not the finalised version.
-  If a dataset has an allowable_use score of either Gold || Platinum we can set the dataset to be available for commerical use. Carries the heaviest weight.
-  If the dataUtility allowable_use score isn’t available we are only checking the field data_use_limitation for “COMMERCIAL RESEARCH USE || NO RESTRICTIONS“. Otherwise commerical use will be set to false.
For the mean time we are **ignoring data_use_requirements until further notice.** **Nothing is to override the …
> IG-1661 Added commercial usage filter

- src/resources/filters/filters.service.js
Filter fix
Filter fix for spreading in publisher, publisher was being replaced in datautility. Moved publisher to bottom of the new spread object.
> Fix dataset filter - publisher 

- src/resources/message/message.controller.js
- src/resources/utilities/emailGenerator.util.js
[IG-1927](https://hdruk.atlassian.net/browse/IG-1927)
- Email sent to notify of messages on the gateway updated to the new email format and to have the HDR logo
- Sub title differs based on if it's a first message
- Link to site with messages open
First message example in outlook:
Following message from data custodian on gmail:
> IG-1927 First message and message emails updated

- src/resources/team/team.controller.js
**Issue**
Upon submitting a first message and further messages to a Custodian team, under certain circumstances, the submitter would not be emailed a receipt of their message.
- Fixed erroneous filter which was removing the applicant as they were effectively not seen as part of the team to be emailed when default team notifications had been modified.
> First message email fix for missing notification to submitter

- src/config/server.js
Charles has asked for search.healthdatagateway.org and api.healthdatagateway.org to be domains for production (they are both active - but failing because of cors issues).  This looks like a simple way to get it work without significant rework,
I am slightly sceptical however as i dont see the Access-Control-Allow-Origin header from the API when making a call.
> Trust all healthdatagateway.org domains to be able to access API

- src/config/server.js
- src/resources/cohortprofiling/cohortprofiling.controller.js
- src/resources/cohortprofiling/cohortprofiling.model.js
- src/resources/cohortprofiling/cohortprofiling.repository.js
- src/resources/cohortprofiling/cohortprofiling.route.js
- src/resources/cohortprofiling/cohortprofiling.service.js
- src/resources/cohortprofiling/dependency.js
Example 1 can be used for front end to drive stars logic.  
Example 2 and 3 use the second end point to get frequency data about the values for a given variable within a table belonging to a dataset.
Example uses:
1.  Get List of tableNames and variables with profiling data for a given pid
http://localhost:3001/api/v2/cohortProfiling?pids=4ef841d3-5e86-4f92-883f-1015ffd4b979&fields=variables.name, tableName,variables.completeness
2. Get profiling data for a single variable given a pid and tableName and variable (top 10 ordered by frequency descending)
http://localhost:3001/api/v2/cohortProfiling/4ef841d3-5e86-4f92-883f-1015ffd4b979/Clinical/var2
3. Get profiling data for a single variable given a pid and tableName and variable.  Filter by value 'yza', sort by value descending and limit to …
> 2 new endpoints created for Cohort Profiling

- src/resources/activitylog/__mocks__/activitylogs.js
- src/resources/activitylog/__tests__/activitylog.service.test.js
- src/resources/activitylog/activitylog.service.js
- src/resources/datarequest/datarequest.repository.js
Activity log should display the number of days since a version was submitted along with the % time spent with applicants vs custodians.
- Added time calculation for parties to activity log output for each major and minor version including unit tests for calculation logic.
> IG-2004 - DAR - Update party time distribution output for application versions

- cloudbuild_dynamic.yaml
- migrations/1628148589241-icoda-migration.js
- migrations/migrate.js
- package.json
These changes are made to support icodara-112. I made these changes:
1.  I added mongoose-migrate package to the ICODA project dependencies.
2. I added the same migrate.js as HDR UK (migrate.js is setting the configurations for mongoose-migrate).
3. I wrote the script to populate a new Team, Publisher and DataRequestSchema(for the ICODA accreditation) to the DB.
4. I added the steps for the migration on our GCP console build file (cloudbuild_dynamic.yaml)
> Icodara 112: Simplified User Journey

- src/resources/datarequest/datarequest.repository.js
- src/resources/utilities/cloudStorage.util.js
Error occurring as a result of versioning data access request applications where a required variable 'versionTree' was not being included in the database query used to determine which applications to update once file upload had completed/changed status.
- Instated missing variable for versioning
- Added conversions from MongoDb ObjectId to string
> SUPP-DAR-Fileupload - Hot fix for file upload error

- src/resources/datarequest/datarequest.repository.js
- src/resources/utilities/cloudStorage.util.js
Error occurring as a result of versioning data access request applications where a required variable 'versionTree' was not being included in the database query used to determine which applications to update once file upload had completed/changed status.
- Instated missing variable for versioning
- Added conversions from MongoDb ObjectId to string
> Fixed file upload error as a result of versioning

- src/resources/auth/auth.route.js
Fix for admin not able to override because they are already a manager/metadata_editor of the team
> Hotfix - Fix for admin not able to override

- src/resources/datarequest/amendment/amendment.service.js
- src/resources/datarequest/datarequest.controller.js
- src/resources/utilities/constants.util.js
- src/resources/utilities/emailGenerator.util.js
Changes requested to amend functionality copy:
[Amend - 03.09.21.pptx](https://github.com/HDRUK/gateway-web/files/7109328/Amend.-.03.09.21.pptx)
Comments from client:
- Any in-line change to a question should be flagged with the wording: Applicant has requested this as an amendment to the approved application on XX date.
- It could read applicant has submitted an amendment request to an approved application (to indicate at this stage it is still only a request and needs to be approved before it becomes an amendment).
- In the first in app notification it could just read “your amendment request was successfully submitted” (i.e., remove ‘with updates’). If anything it should refer to what the approved application reference is.
- Same for custodian view – “An amendment request has been …
> DAR - Amend - Copy changes

- package.json
- src/config/server.js
- src/resources/person/person.route.js
- src/resources/user/user.register.route.js
- src/services/hubspot/hubspot.js
- src/services/hubspot/hubspot.route.js
**Task description**
Switch integration from MailChimp to Hubspot for managing communication preferences to allow mailing campaigns.
Agreed with HDR to use HubSpot custom ‘Communication preference’ property to record users/contacts active opt status against the Gateway News and Feedback comms options.
**Development/Completed**
- Replacement of MailChimp connector with HubSpot specific implementation, interfacing with the API at the same key points e.g. registration and profile update.
- Batch imported contacts who have currently opted in to feedback on the Gateway.
- Added ‘Gateway Registered User’ property as true to all Hubspot contacts existing on the Gateway.
**For Go-Live**
- Update the nightly job which keeps subscriptions in sync between HubSpot and the Gateway to point at new API …
> IG-2207 - Switch MailChimp Integration to HubSpot

- migrations/1631633422670-message_user_types.js
In order to produce a MongoDb chart illustrating the usage of the first message feature, we need to add the user type to existing data in production.  With the user type added, we are able to determine if a custodian team has responded to an enquiry.
- Created script to determine if the sender of each message either a custodian or an applicant and updates accordingly.
> IG-2300 - Migration script to add sender user type to existing messages

- src/config/server.js
**Issue**
Error occurring posting forms from Gateway React UI to API due to not providing valid CSRF token.  API implementation and expectation of CSRF must happen in sync with UI implementation.  This was introduced as a security recommendation by LGTM.
**Error**
`ForbiddenError: invalid csrf token
[0]     at csrf (/HDR-UK/gateway-api/node_modules/csurf/index.js:112:19)`
**Fix**
- Remove CSRF validation initialisation from Node server config.
> Bug fix - removed CSRF validation

- src/resources/message/message.controller.js
- src/resources/team/team.controller.js
- src/resources/topic/topic.controller.js
**Issue**
Reported by ONS that some of their team members were receiving unexpected messages relating to data access requests, when they were responsible only for metadata editing.
**Investigation**
After determining that the users were not in the role of manager and should therefore not have received the messages, we looked at the latest feature development in this area which was to allow opt in/out for individual users and add generic team notifications.  By replicating the problem described, we were able to pinpoint a bug which was including all team members if they were opted in to data access request emails.  The metadata editors should not have been opted in and as an additional step, only managers and reviewers for data access request should be included.
- Updated …
> SUPP-656 - Fix for incorrect message access for custodian teams

- src/resources/message/message.controller.js
- src/resources/team/team.controller.js
- src/resources/topic/topic.controller.js
**Issue**
Reported by ONS that some of their team members were receiving unexpected messages relating to data access requests, when they were responsible only for metadata editing.
**Investigation**
After determining that the users were not in the role of manager and should therefore not have received the messages, we looked at the latest feature development in this area which was to allow opt in/out for individual users and add generic team notifications. By replicating the problem described, we were able to pinpoint a bug which was including all team members if they were opted in to data access request emails. The metadata editors should not have been opted in and as an additional step, only managers and reviewers for data access request should be included.
- Updated …
> SUPP-656 - Fixed incorrect message access for team members

- src/resources/base/entity.js
- src/resources/dataUseRegister/__mocks__/dataUseRegisterUsers.js
- src/resources/dataUseRegister/__mocks__/dataUseRegisters.js
- src/resources/dataUseRegister/__tests__/dataUseRegister.service.test.js
- src/resources/dataUseRegister/__tests__/dataUseRegister.util.test.js
- src/resources/dataUseRegister/dataUseRegister.controller.js
- src/resources/dataUseRegister/dataUseRegister.entity.js
- src/resources/dataUseRegister/dataUseRegister.model.js
- src/resources/dataUseRegister/dataUseRegister.repository.js
- src/resources/dataUseRegister/dataUseRegister.route.js
- src/resources/dataUseRegister/dataUseRegister.service.js
- src/resources/dataUseRegister/dataUseRegister.util.js
- src/resources/dataset/dataset.repository.js
- src/resources/dataset/dataset.service.js
- src/resources/user/user.repository.js
**Description**
Introducing a new endpoint to the Data Use Register API to allow the bulk upload of data uses via a spreadsheet on the front end.  Majority of validation is carried out on front end as the spreadsheet is parsed.  The backend validation is limited to the Mongoose model definition which is set specifically to not be 'strict'.  The upload validation can be circumvented by an administrator of the Gateway application, meaning the backend validation must be more forgiving.
New data uses are uploaded against the team specified in the payload and are appended with a flag indicating the source was a manual upload in the 'manualUpload' boolean property of the model.
Users have the capability to provide URLs pointing to the Gateway in order to link specific datasets and applicants to …
> IG-2271 - Data Use Register Bulk Upload API

- src/config/middleware.js
- src/resources/base/repository.js
- src/resources/cohort/cohort.route.js
- src/resources/cohortprofiling/cohortprofiling.route.js
- src/resources/course/v2/course.route.js
- src/resources/dataset/v2/dataset.route.js
- src/resources/paper/v2/paper.route.js
- src/resources/project/v2/project.route.js
- src/resources/tool/v2/tool.route.js
- swagger.yaml
- test/middleware.test.js
**Issue**
Requesting data from public facing GET endpoint '/api/v2/datasets' was throwing error once the response size exceeded 80mb.  Work around for the batch export of datasets was provided using the existing base entity and mongoose implementation allowing a page and limit query param to be passed.  e.g. '/api/v2/datasets?page=1&limit=100'.  
**Solution**
It was recommended that these public facing endpoints should have a record limit of 100, applying to all v2 endpoints, not just datasets.
- Added middleware function to challenge 'limit' query string entry
- Set a maximum request size (limit) in the base repository to 500 records when no limit is defined by middleware
- Added unit tests for middleware function
- Updated all v2 entity GET all routes to implement …
> SUPP-655 - Response limiting for API v2 entity endpoints

- src/resources/dataset/datasetonboarding.controller.js
This small change allows the listOfVersions to appear on the admin datasets API so that the version IDs can be passed to the activity log API.
Previously the listOfVersions for the admin datasets page came back blank for all datasets.
> CR - admin publisher to return all versions

- src/middlewares/__tests__/datasetonboarding.middleware.test.js
- src/middlewares/datasetonboarding.middleware.js
- src/resources/dataset/datasetonboarding.controller.js
- src/resources/dataset/utils/__tests__/datasetonboarding.util.test.js
- src/resources/dataset/utils/datasetonboarding.util.js
- src/resources/utilities/constants.util.js
Adding the option to sort by popularity (i.e., most-viewed) for active datasets.
> Add sort by most viewed for active datasets

- docs/resources/dataset.docs.js
- src/controllers/__tests__/datasetonboarding.controller.test.js
- src/controllers/datasetonboarding.controller.js
- src/middlewares/__tests__/datasetonboarding.middleware.test.js
- src/middlewares/datasetonboarding.middleware.js
- src/services/__tests__/datasetonboarding.service.test.js
- src/services/datasetonboarding.service.js
Removing pagination ability from search/sort story (this functionality will be added to separate story).
> Remove pagination from search/sort datasets API

- src/controllers/__tests__/datasetonboarding.controller.test.js
- src/controllers/datasetonboarding.controller.js
- src/middlewares/__tests__/datasetonboarding.middleware.test.js
- src/middlewares/datasetonboarding.middleware.js
- src/services/__tests__/datasetonboarding.service.test.js
- src/services/datasetonboarding.service.js
Fixes a defect where the draft datasets were not shown alongside the live datasets on the custodian/HDR admin dashboard.
Changes to endpoint so that the dataset-onboarding GET can accept a comma-delimited list of statuses instead of one, e.g., status=active,draft, minimising the number of requests that are required from the FE.
Changed to middleware functions to return a 400 in the case of an invalid param (instead of 500).
Fixes to relevant tests.
> release-fix/GAT-646

- src/services/__mocks__/datasetSearchStub.js
- src/services/__tests__/datasetonboarding.service.test.js
- src/services/datasetonboarding.service.js
Fixes an issue where a duplicated dataset had matching 'datasetid' fields to their root, causing propagated errors.
Fixed by adding temp string for datasetid, which is replaced when the dataset is approved.
Added test.
> release-fix/GAT-655

- src/resources/utilities/constants.util.js
- src/services/datasetonboarding.service.js
Metadata sorting caused datasets with the same metadata score to be randomly sorted. This fix add the timestamps.updated as the secondary sort such that the datasets will first be sorted on the chosen sort option, and then secondary by the updated time.
> release-fix/GAT-725

- src/resources/utilities/constants.util.js
- src/services/__mocks__/datasetSearchStub.js
- src/services/__tests__/datasetonboarding.service.test.js
- src/services/datasetonboarding.service.js
Sorting by metadata was sorting on the wrong field.
This updates sorts on the metadata quality score. Because this field is sometimes a string, use the Mongo conversion feature. Datasets with no score are sorted as if they had a score of 0.
Datasets with the same score are secondary sorted on their updated time.
> release-fix/GAT-733

- src/resources/utilities/wordTemplateBuilder.util.js
New env variable required:
GOOGLE_WORD_OUTBOUND_STORAGE_BUCKET="<bucket name>"
> Remove the google storage bucket name into a env variable - GAT-774

- src/resources/utilities/__tests__/emailGenerator.util.test.js
- src/resources/utilities/emailGenerator.util.js
- src/utils/datasetonboarding.util.js
Adds an additional line to emails sent when a dataset is rejected warning the custodian that they must update their dataset in their own catalogue. Only appears in email if custodian is federated, otherwise emails same as before.
> feature/GAT-948 - federated warning in reject emails if custodian is federated

- src/resources/team/team.controller.js
Change to the add team API to include the new _id in the response so that we can use the resultant ID to update the question bank status for that new team...
> GAT-1300 - fix for creating new team

- src/resources/utilities/emailGenerator.util.js
fixes a bug where email attachments were not encoded properly after switching to nodemail from the SendGrid API...
> release-fix/GAT-1313

- src/resources/questionbank/__tests__/questionbank.service.test.js
- src/resources/search/search.repository.js
Fixes bug where metadata ordering was not working properly because the metadata quality score was in string format for some datasets. Also fixes a broken unit test.
> Fix metadata ordering of search results
